
<?php
$user= $_SESSION['user'];

$task = new TasksController;
$taskname='';

if($_SESSION['check']) $_SESSION['msg']="User successfully registered!";
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>simple todo</title>
</head>
<body>
<div class="w-3/4 text-center mx-auto">
          <div class="w-full mt-5">
      <label class="md:text-xl text-sm text-white font-bold" for="username">Tasklist of user: <label class="text-teal-999"><?php echo $user;?></label></label>
          </div>
          <div class="md:text-base text-xs w-full mt-5">
         <form class="mx-auto my-5" action="" method="POST">
         
                <input class="w-3/4 shadow appearance-none border rounded  text-gray-700 leading-tight my-2 mx-2 py-2 px-3
                focus:shadow-outline" id="taskname" type="text" placeholder="Enter task name" name="taskname" required>
      
                <input class="shadow appearance-none border rounded  text-gray-700 leading-tight my-2 mx-2 py-2 px-3
                focus:shadow-outline" id="endDate" type="date" name="endDate" required>

                <button class="bg-teal-700 hover:bg-teal-500 text-white font-bold rounded
                focus:shadow-outline my-2 mx-2 py-2 px-3" type="submit" value="Add task" name="addtask">Add task</button>
        </form>
          </div>
</div>
<div class="flex flex-row w-3/4 md:text-base text-xs text-white font-bold border rounded mx-auto my-2">
      
      <div class="mx-auto w-2/12 text-center my-auto">
      Task status
      </div>
      <div class="mx-auto w-2/12 text-center my-auto">
      Strating date
      </div>
      <div class="mx-auto w-2/12 text-center my-auto">
      Ending date
      </div>
      <div class="mx-auto  w-4/12 text-center my-auto">
      Task name
      </div>
      <div class="mx-auto  w-2/12 text-center my-auto">
      Delete task
      </div>
</div>

    <div class="w-3/4 my-auto mx-auto">
    
<?php    
      if($task->tasksArray()){
      foreach($task->tasksArray() as $task): 
            $taskname = $task['taskname'];
         
      switch ($task['completed']){  
     
      case 1:
            $button_color="teal";
            $button_text="Proceeding";
            break;
      case 2:
            $button_color="emerald";
            $button_text="Done";
            break;
      default:
            $button_color="red";
            $button_text="Not done";
            }
?>       
<div class="flex flex-row w-full md:text-base text-xs text-white font-bold border rounded my-2">
          <form class="table w-2/12 text-center m-auto" action="" method="POST">
          <input type="hidden" name="marktask" value="<?php echo $taskname ?>">
          <button class="bg-<?php echo $button_color ?>-500 hover:bg-<?php echo $button_color ?>-700 
          py-2 px-1  w-24 rounded focus:shadow-outline my-2 mx-5"><?php echo $button_text ?></button>
          </form> 

          <div class="m-auto w-2/12 text-center">
          <?php echo $task['date']?>
          </div>
          <div class="m-auto w-2/12 text-center">
          <?php echo $task['endDate']?>
          </div>

          <div class="m-auto  w-4/12 text-center">
          <?php echo $taskname ?>
          </div>

          <form class="table w-2/12 text-center m-auto" action="" method="POST">
          <input type="hidden" name="deltask" value="<?php echo $taskname?>">
          <button class="bg-red-500 hover:bg-red-700 py-2 px-3 w-24 rounded 
          focus:shadow-outline my-2 mx-5">Delete</button>
          </form>
</div>
        <?php endforeach;}?>

    </div>

      <div class="w-full text-center my-10">
      <h3 class="md:text-xl text-sm text-teal-300 font-bold "><?php echo $_SESSION['msg'] ?></h3>
      </div>

</body>
</html>


      