
<?php
//session_start();

$user=$_SESSION['user'];
//$_SESSION['msg']='';
$taskname='';
$ts='';
$ob='';

?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>simple todo</title>
</head>
<body>
<div class="w-3/4 text-center mx-auto">
          <div class="w-full mt-5">
                <label class="text-white text-xl font-bold" for="username">Tasklist of user: <label class="text-teal-500"><?php echo $user;?></label></label>
          </div>
          <div class="w-full mt-5">
         <form class="w-full mx-auto my-5" action="" method="POST">
                <input class="w-10/12 shadow appearance-none border rounded  text-gray-700 leading-tight my-2 mx-2 py-2 px-3
                focus:outline-none focus:shadow-outline" id="taskname" type="text" placeholder="Enter task name" name="taskname" required>
      
                <button class="bg-teal-500 hover:bg-teal-700 text-white font-bold rounded focus:outline-none
                focus:shadow-outline my-2 mx-2 py-2 px-3" type="submit" value="Add task" name="addtask">Add task</button>
        </form>
          </div>
</div>


    <div class="w-3/4 my-auto mx-auto">
    <div>
        
<?php       
      if(file_exists($tr=ROOT_PATH . "/db/tasks." . $user . ".json")) {
          
      $tasksArray=json_decode(file_get_contents($tr), true);
      
      foreach($tasksArray as $task): 
      $button_color="teal";
      $taskname=$task['taskname'];
      $button_text="Done";
      if(!$task['completed']){
      $button_color="red";
      $button_text="Not done";
      }
?>       
<div class="flex flex-wrap w-full text-white font-bold border rounded my-2">
          <form class="w-2/12 text-center my-auto" action="" method="POST">
          <input type="hidden" name="marktask" value="{{ $taskname }}">
          <button class="bg-<?php echo $button_color ?>-500 hover:bg-<?php echo $button_color ?>-700 font-bold py-2 px-3 w-24 rounded focus:outline-none
            focus:shadow-outline my-2 mx-5"><?php echo $button_text ?></button>
          </form> 

          <div class="mx-auto w-3/12 text-left my-auto">
          <?php echo $task['date']?>
          </div>

          <div class="mx-auto  w-5/12 text-left my-auto">
          <?php echo $taskname ?>
          </div>

          <form class="w-2/12 text-center my-auto" action="" method="POST">
          <input type="hidden" name="deltask" value="<?php echo $taskname?>">
          <button class="bg-red-500 hover:bg-red-700 font-bold py-2 px-3 w-24 rounded focus:outline-none
                focus:shadow-outline my-2 mx-5">Delete</button>
          </form>
</div>
        <?php endforeach;}?>

    </div>
    </div>

      <div class="w-full text-center my-10">
      <h3 class="text-xl text-teal-300 font-bold "><?php echo $_SESSION['msg'] ?></h3>
      </div>

</body>
</html>


      