
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>simple todo</title>
</head>
<body>

<div class="h-2/6 w-3/4 text-center mx-auto mt-14">
 
        <form class="rounded px-8 pt-6 pb-8 mb-4 w-4/12  m-auto" action="login" method="POST" id="signup-form">
          
            <div>
                <label class="block text-white text-sm font-bold mb-4" for="username">Username</label>
                <input class="shadow appearance-none border rounded w-full py-2 px-3 mb-3 text-gray-700 leading-tight 
                focus:outline-none focus:shadow-outline" id="username" type="text" placeholder="username" name="username" required>
            </div>
            <div class="mt-4 mb-2">
                <label class="block text-white text-sm font-bold mb-4" for="password">Password</label>
                <input class="shadow appearance-none border border-red-500 rounded w-full py-2 px-3 text-gray-700 mb-3 
                leading-tight focus:outline-none focus:shadow-outline" id="password" type="password" placeholder="**********" name="pwd" required>
            </div>

            <div class="flex flex-row justify-between">
                 
                <input class="bg-teal-500 hover:bg-teal-700 text-white font-bold py-2 px-3 rounded focus:outline-none
                focus:shadow-outline" type="submit" value="Sign In" name="signin">
                
                <input class="bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-3 rounded focus:outline-none
                focus:shadow-outline" type="submit" value="Sign Up" name="signup">
            
            </div>
        
</div>
        </form>      
        <div class="w-3/4 text-center mx-auto">
      <h3 class="text-xl text-teal-300 font-bold mt-10"><?php echo $_SESSION['msg'] ?></h3>
      </div>

<?php 

?>

