
<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>simple todo</title>
  <link rel="stylesheet" type="text/css" href="./web/stylesheets/output.css">
</head>
<body class="p-4  bg-cyan-700">
<div  class="md:text-base text-xs text-white w-3/4 font-bold text-right mx-auto">
<form action="./index" method="POST">
<?php
if (isset($_SESSION['user'])) {echo('<button type="submit" value="Sign out" name="signout">Sign out</button>');}
?>
</form>
</form>
</div>
<div class="w-3/4 text-center mx-auto">
  <h3 class="md:text-xl text-sm text-white font-bold">TODO APP HEADER</h3>
 </div>

</body>
