
<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>simple todo</title>
  <link rel="stylesheet" type="text/css" href="./web/stylesheets/output.css">
</head>
<body class="p-4  bg-cyan-700">
<div  class="w-3/4 text-white text-sm font-bold text-right mx-auto">
<form action="./"  method="POST">
<button class="text-white font-bold" type="submit" value="Sign out" name="signout">Sign out</button>
</form>
</form>
</div>
<div class="w-3/4 text-center mx-auto">
  <h3 class="text-xl text-white font-bold">TODO APP HEADER</h3>
 </div>

</body>
